### ISSUE TITLE
按照文档步骤操作，未生成可执行的ARK包

### ISSUE THREAD

**Issue by zerochina2020** [sofastack-guides/sofa-ark-dynamic-guides#4]
@lvjing2 体验示例遇到如下问题，烦请指导
1、按照README中的步骤操作，未生成可执行的ARK包，如下图
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/11956058/158610312-6485042b-a39c-4588-9d0b-24088d0e8a1f.png">
2、部分依赖提示not found，是否缺少什么配置，如下图
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/11956058/158611468-b9a12451-403e-402d-a71e-e666252f0674.png">
3、IDEA中启动，未按预期启动Ark container
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/11956058/158613906-c06af2d5-3bc8-46ea-abcc-e19179209425.png">

**Comment by lvjing2** [comment]
@zerochina2020 SOFAArk 2.0之后已经不需要可执行的ark biz包了
关于本地启动没有启动 ark container的问题，你看下console日志里有没有 `Ark container started in`, 也可以本地terminal执行 `telnet 127.0.0.1 1234` 检查是否启动ark成功。
